import React, { useState, useEffect } from 'react';
import { FileText, Download, Printer, Shield, AlertTriangle, CheckCircle, Clock, ArrowRight } from 'lucide-react';
import { generateBrief } from '../../services/api';
import type { ExecutiveBrief as BriefData } from '../../types';
import { getAQIColor } from '../../utils/formatters';

interface ExecutiveBriefProps {
  cityId: string;
}

export default function ExecutiveBrief({ cityId }: ExecutiveBriefProps) {
  const [brief, setBrief] = useState<BriefData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    generateBrief(cityId)
      .then(setBrief)
      .catch(err => setError(err.message))
      .finally(() => setLoading(false));
  }, [cityId]);

  const handlePrint = () => {
    window.print();
  };

  const handleExport = () => {
    const content = document.getElementById('brief-content');
    if (!content) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>${brief?.title || 'Executive Brief'}</title>
          <style>
            body { font-family: Inter, system-ui, sans-serif; color: #0f172a; padding: 40px; line-height: 1.6; }
            h1 { font-size: 24px; margin-bottom: 8px; }
            h2 { font-size: 18px; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
            h3 { font-size: 14px; margin-top: 16px; margin-bottom: 8px; color: #475569; }
            p { font-size: 13px; color: #475569; margin-bottom: 8px; }
            .metric { display: inline-block; padding: 8px 16px; background: #f8fafc; border-radius: 8px; margin: 4px; }
            .metric-label { font-size: 11px; color: #94a3b8; }
            .metric-value { font-size: 20px; font-weight: 700; }
            .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
            table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 12px 0; }
            td, th { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; text-align: left; }
            th { color: #64748b; font-size: 11px; text-transform: uppercase; }
            .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
            .rec { display: flex; gap: 12px; padding: 12px; background: #f8fafc; border-radius: 8px; margin-bottom: 8px; }
            .priority-CRITICAL { background: #fee2e2; color: #dc2626; }
            .priority-HIGH { background: #ffedd5; color: #ea580c; }
            .priority-MEDIUM { background: #dbeafe; color: #2563eb; }
            .priority-LOW { background: #f0fdf4; color: #16a34a; }
          </style>
        </head>
        <body>
          ${content.innerHTML}
          <div class="footer">
            <p>Generated by UrbanBreathe Command Centre • ${new Date().toLocaleString('en-IN')}</p>
            <p>CONFIDENTIAL — For official use only</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); }, 500);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-pulse-soft text-slate-400 text-sm">Generating executive brief...</div>
      </div>
    );
  }

  if (error || !brief) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="text-red-500 text-sm">Error generating brief: {error || 'Unknown error'}</div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header Actions */}
      <div className="flex items-center justify-between no-print">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-brand-50 flex items-center justify-center">
            <FileText size={18} className="text-brand-600" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-slate-900">Executive Decision Brief</h2>
            <p className="text-sm text-slate-500">Government-ready situational report</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-600 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors"
          >
            <Printer size={14} /> Print
          </button>
          <button
            onClick={handleExport}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-white bg-brand-500 rounded-lg hover:bg-brand-600 transition-colors"
          >
            <Download size={14} /> Export PDF
          </button>
        </div>
      </div>

      {/* Print-only header */}
      <div className="hidden print:block text-center mb-4">
        <h1 className="text-xl font-bold text-slate-900">UrbanBreathe Command Centre</h1>
        <p className="text-sm text-slate-500">Air Quality Decision Intelligence Platform</p>
      </div>

      {/* Brief Content */}
      <div id="brief-content" className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        {/* Header Banner */}
        <div className="px-6 py-4 border-b border-slate-100 bg-gradient-to-r from-slate-50 to-white">
          <div className="flex items-center gap-2 text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-2">
            <Shield size={12} />
            {brief.classification}
          </div>
          <h3 className="text-xl font-bold text-slate-900">{brief.title}</h3>
          <div className="flex items-center gap-4 mt-2 text-xs text-slate-500">
            <span>{brief.date}</span>
            <span className="flex items-center gap-1"><Clock size={11} /> Generated {new Date(brief.generatedAt).toLocaleTimeString()}</span>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="px-6 py-5 border-b border-slate-100">
          <h4 className="text-sm font-semibold text-slate-800 mb-3">1. Executive Summary</h4>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div className="bg-slate-50 rounded-lg p-3 text-center">
              <div className="text-xs text-slate-500 mb-1">Current AQI</div>
              <div className="text-2xl font-bold" style={{ color: getAQIColor(brief.executiveSummary.currentAQI) }}>
                {brief.executiveSummary.currentAQI}
              </div>
              <div className="text-xs font-medium text-slate-600">{brief.executiveSummary.category}</div>
            </div>
            <div className="bg-slate-50 rounded-lg p-3 text-center">
              <div className="text-xs text-slate-500 mb-1">Trend</div>
              <div className="text-lg font-bold text-slate-700">{brief.executiveSummary.trend}</div>
              <div className="text-xs text-slate-500">{brief.executiveSummary.season}</div>
            </div>
            <div className="bg-slate-50 rounded-lg p-3 text-center">
              <div className="text-xs text-slate-500 mb-1">Dominant</div>
              <div className="text-lg font-bold text-slate-700">{brief.executiveSummary.dominantPollutant}</div>
              <div className="text-xs text-slate-500">Pollutant</div>
            </div>
            <div className={`rounded-lg p-3 text-center ${
              brief.executiveSummary.criticality === 'CRITICAL' ? 'bg-red-50' :
              brief.executiveSummary.criticality === 'HIGH' ? 'bg-orange-50' : 'bg-slate-50'
            }`}>
              <div className="text-xs text-slate-500 mb-1">Criticality</div>
              <div className={`text-lg font-bold ${
                brief.executiveSummary.criticality === 'CRITICAL' ? 'text-red-600' :
                brief.executiveSummary.criticality === 'HIGH' ? 'text-orange-600' : 'text-slate-600'
              }`}>
                {brief.executiveSummary.criticality}
              </div>
              <div className="text-xs text-slate-500">Level</div>
            </div>
          </div>
        </div>

        {/* Current Situation */}
        <div className="px-6 py-5 border-b border-slate-100">
          <h4 className="text-sm font-semibold text-slate-800 mb-2">2. Current Situation</h4>
          <p className="text-sm text-slate-600 leading-relaxed mb-3">{brief.currentSituation.overview}</p>
          <div className="grid grid-cols-3 md:grid-cols-6 gap-2">
            {Object.entries(brief.currentSituation.keyMetrics).slice(0, 6).map(([key, val]) => (
              <div key={key} className="bg-slate-50 rounded p-2 text-center">
                <div className="text-[10px] text-slate-500 uppercase font-medium">{key}</div>
                <div className="text-sm font-semibold text-slate-700">{val}</div>
              </div>
            ))}
          </div>
          <div className="mt-3 space-y-1">
            {brief.currentSituation.weatherInfluence.map((w, i) => (
              <div key={i} className="flex items-center gap-2 text-xs text-slate-500">
                <AlertTriangle size={10} className="text-amber-500" />
                {w}
              </div>
            ))}
          </div>
        </div>

        {/* Source Attribution */}
        <div className="px-6 py-5 border-b border-slate-100">
          <h4 className="text-sm font-semibold text-slate-800 mb-2">3. Source Attribution</h4>
          <p className="text-sm text-slate-600 mb-3">{brief.sourceAttribution.keyFinding}</p>
          <div className="space-y-2">
            {brief.sourceAttribution.topSources.map((s, i) => (
              <div key={i} className="flex items-center gap-3">
                <span className="w-6 text-xs font-semibold text-slate-400">{i + 1}.</span>
                <div className="flex-1">
                  <div className="flex justify-between text-xs mb-1">
                    <span className="font-medium text-slate-700 capitalize">{s.source}</span>
                    <span className="text-slate-500">{s.percentage}% (conf: {s.confidence}%)</span>
                  </div>
                  <div className="w-full bg-slate-100 rounded-full h-1.5">
                    <div className="h-1.5 rounded-full bg-brand-500" style={{ width: `${s.percentage}%` }} />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Forecast */}
        <div className="px-6 py-5 border-b border-slate-100">
          <h4 className="text-sm font-semibold text-slate-800 mb-2">4. Forecast</h4>
          <p className="text-sm text-slate-600">{brief.forecast.summary}</p>
          <div className="flex items-center gap-4 mt-2 text-xs text-slate-500">
            <span>Peak AQI: <strong>{brief.forecast.peakAQI}</strong></span>
            <span>Confidence: <strong>{brief.forecast.confidence}%</strong></span>
            <span>Trend: <strong>{brief.forecast.trend}</strong></span>
          </div>
        </div>

        {/* Recommendations */}
        <div className="px-6 py-5 border-b border-slate-100">
          <h4 className="text-sm font-semibold text-slate-800 mb-3">5. Recommendations</h4>
          <div className="space-y-3">
            {brief.recommendations.map((r, i) => (
              <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-slate-50">
                <div className={`mt-0.5 p-1 rounded ${
                  r.priority === 'CRITICAL' ? 'bg-red-100 text-red-600' :
                  r.priority === 'HIGH' ? 'bg-orange-100 text-orange-600' :
                  'bg-blue-100 text-blue-600'
                }`}>
                  {r.priority === 'CRITICAL' ? <AlertTriangle size={14} /> : <CheckCircle size={14} />}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-slate-800">{r.action}</span>
                    <span className={`px-1.5 py-0.5 rounded text-[10px] font-semibold ${
                      r.priority === 'CRITICAL' ? 'bg-red-100 text-red-700' :
                      r.priority === 'HIGH' ? 'bg-orange-100 text-orange-700' :
                      'bg-blue-100 text-blue-700'
                    }`}>
                      {r.priority}
                    </span>
                  </div>
                  <div className="flex items-center gap-3 mt-1 text-xs text-slate-500">
                    <span className="flex items-center gap-1"><Clock size={10} /> {r.timeline}</span>
                    <span className="flex items-center gap-1"><ArrowRight size={10} /> {r.expectedImpact}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Expected Outcomes */}
        <div className="px-6 py-5 border-b border-slate-100">
          <h4 className="text-sm font-semibold text-slate-800 mb-3">6. Expected Outcomes</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {brief.expectedOutcomes.withIntervention && (
              <div className="bg-teal-50 rounded-lg p-4 border border-teal-100">
                <div className="flex items-center gap-1.5 text-xs font-semibold text-teal-700 mb-2">
                  <CheckCircle size={12} /> With Intervention
                </div>
                <div className="space-y-1 text-sm">
                  <div className="flex justify-between"><span className="text-teal-600">AQI</span><span className="font-semibold">{brief.expectedOutcomes.withIntervention.aqi}</span></div>
                  <div className="flex justify-between"><span className="text-teal-600">Reduction</span><span className="font-semibold">-{brief.expectedOutcomes.withIntervention.reduction}</span></div>
                  <div className="flex justify-between"><span className="text-teal-600">PM2.5</span><span className="font-semibold">{brief.expectedOutcomes.withIntervention.pm25} µg/m³</span></div>
                  <div className="flex justify-between"><span className="text-teal-600">Admissions Averted</span><span className="font-semibold">{brief.expectedOutcomes.withIntervention.admissionsAverted}</span></div>
                  <div className="flex justify-between"><span className="text-teal-600">Cost</span><span className="font-semibold">₹{brief.expectedOutcomes.withIntervention.cost}Cr</span></div>
                </div>
              </div>
            )}
            <div className="bg-orange-50 rounded-lg p-4 border border-orange-100">
              <div className="flex items-center gap-1.5 text-xs font-semibold text-orange-700 mb-2">
                <AlertTriangle size={12} /> Without Intervention
              </div>
              <div className="space-y-1 text-sm">
                <div className="flex justify-between"><span className="text-orange-600">AQI</span><span className="font-semibold">{brief.expectedOutcomes.withoutIntervention.aqi}</span></div>
                <div className="flex justify-between"><span className="text-orange-600">PM2.5</span><span className="font-semibold">{brief.expectedOutcomes.withoutIntervention.pm25.toFixed(0)} µg/m³</span></div>
                <div className="flex justify-between"><span className="text-orange-600">Risk Level</span><span className="font-semibold">{brief.expectedOutcomes.withoutIntervention.riskLevel}</span></div>
              </div>
            </div>
          </div>
        </div>

        {/* Public Advisory & Footer */}
        <div className="px-6 py-5">
          <h4 className="text-sm font-semibold text-slate-800 mb-2">7. Public Advisory</h4>
          <p className="text-sm text-slate-600 mb-4">{brief.publicAdvisory}</p>

          <div className="flex items-center justify-between pt-4 border-t border-slate-100 text-xs text-slate-400">
            <span>Confidence: {brief.confidenceLevel}</span>
            <span>{brief.methodology}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
